class_name InvItem
extends TextureButton
## Used to store data in item [TextureButton]s. Logic is handled by the parent [InventoryHelper] inventory.
##
## A base item is the item's default instance. An assembled item is a modified base item.
## Inventories accept assembled items, not base items. [br]
## [br]
## [b]Base Item Indexes:[/b] [br]
## 0 is item name, [br]
## 1 is type, [br]
## 2 is max value, [br]
## 3 is hydration value, [br]
## 4 is satiation value, [br]
## 5 is flavour text [br]
## 6 (Prefer -2) is the shrunken texture [br]
## 7 (Prefer -1) is the normal texture [br]
## [br]
## [b]Assembled Item Indexes:[/b] [br]
## 0 is the base item, [br]
## 1 is the quality, which the last three are calculated from, [br]
## 2 is the display name - generated, easter egg, etc., [br]
## 3 is the value, [br]
## 4 is hydration, [br]
## 5 is satiation [br]
## [br]
## Values with "null" or 0 do not have that property/value attached to the item. [br]

## Stores the assembledItem. [br]
## [br]
## [b]Assembled Item Indexes:[/b] [br]
## 0 is the base item, [br]
## 1 is the quality, which the last three are calculated from, [br]
## 2 is the display name - generated, easter egg, etc., [br]
## 3 is the value, [br]
## 4 is hydration, [br]
## 5 is satiation [br]
## [br]
@export var assembledItem = []
## Stores the baseItem. [br]
## [br]
## [b]Base Item Indexes:[/b] [br]
## 0 is item name, [br]
## 1 is type, [br]
## 2 is max value, [br]
## 3 is hydration value, [br]
## 4 is satiation value, [br]
## 5 is flavour text [br]
## 6 (Prefer -2) is the shrunken texture [br]
## 7 (Prefer -1) is the normal texture [br]
@export var baseItem = []
## Stores whether the button is pressed.
@export var isPressed = false
