extends Node2D

var marketOpen = false

@onready var productList = get_node("pickProduct/productList")
@onready var buyButton = get_node("pickProduct/buyButton/interactable")
@onready var buyButtonContainer = get_node("pickProduct/buyButton")
@onready var stallNameDisplay = get_node("pickProduct/directive")
@onready var ownerPortraitSprite = get_node("pickProduct/ownerPortrait")
@onready var ownerNameLabel = get_node("pickProduct/ownerName")

@onready var ledger = get_node("../Ledger")
@onready var inventory = get_node("../inventoryWind")
@onready var dialogueLib = get_node("../sellWind/postApproach/minigameWindows")
@onready var clock = get_node("../../digitalClock")

@onready var itemDesc = get_node("pickProduct/itemDesc")
@onready var itemIcon = get_node("pickProduct/itemDesc/itemIcon")
@onready var itemName = get_node("pickProduct/itemDesc/Item")
@onready var infoBarOne = get_node("pickProduct/itemDesc/infoBarOne")
@onready var itemQuality = get_node("pickProduct/itemDesc/infoBarOne/Quality")
@onready var itemValue = get_node("pickProduct/itemDesc/infoBarOne/Value")
@onready var flavourText = get_node("pickProduct/itemDesc/flavourText")


var count
var productButton
var productCount
var allStalls = []
var currentStall
var storedStall:int
var productQuality

# 0 name, 1 ownerName, 2 ownerPortrait, 3 texture, 4 lootTable
# if ownerName is "random", randomly generated name, same for ownerPortrait
# lootTable formatting
# inventory.item: weight
# Weight - higher = more frequent.
# Random loot is generated by grabbing random number skewed towards highest number in weight pool.
# Items with weights above generated number are added to an array,
# after which each loot slot randomly picks from the list with equal chances

@onready var broadStreetClinic = newStall("Broad Street Clinic", "Jory Tillman",
	load("res://assets/Sprites/RockBottom/lootSprites/trashCan.png"),
	{
		[
			"Crystal Wash", "Consumable", 60,
			2, 70,
			"A magical cleaning remedy that you totally shouldn't drink.",
			inventory.skincareIconSmall, inventory.skincareIcon
		]: 10,
		[
			"Healing Ointment", "Medication", 8,
			30, "null",
			"Cheap, effective health recovery. Tastes like congealed magic, though.",
			inventory.waterBottleInvIconSmall, inventory.waterBottleInvIcon
		]: 10
	}
)

@onready var snacks = newStall("Snacks", "random",
	"random",
	{
		inventory.sodaCan: 8,
		inventory.waterBottle: 8,
		inventory.cheese: 7,
		inventory.burger: 8,
	}
)

@onready var groceries = newStall("Groceries", "random",
	"random",
	{
		inventory.waterBottle: 7,
		inventory.burger: 5,
		inventory.sodaCan: 8,
		inventory.vegetables: 8,
		inventory.meats: 7,
		inventory.cheese: 8,
		inventory.soySauce: 5,
		inventory.toiletPaper: 7,
		inventory.skincare: 4,
		inventory.soySauce: 4,
	}
)

@onready var tech = newStall("Tech", "random",
	"random",
	{
		inventory.phone : 3,
		inventory.computer: 2,
		inventory.headphones: 6,
		inventory.appliance: 7
	}
)

@onready var convenience = newStall("Convenience", "random",
	"random",
	{
		inventory.waterBottle: 7,
		inventory.pencil: 8,
		inventory.pen: 5,
		inventory.sodaCan: 5,
		inventory.cardboard: 7,
		inventory.soySauce: 4,
		inventory.bag: 4,
		inventory.paper: 8,
	}
)

@onready var clothing = newStall("Clothing", "random", "random",
	{
		inventory.shirt: 7,
		inventory.sunglasses: 6,
		inventory.hat: 6,
		inventory.pants: 7,
		inventory.shorts: 8,
		inventory.hoodie: 8
	}
)

@onready var uniqueStalls = ["Broad Street Clinic"]

@onready var portraits = [
	load("res://assets/Sprites/RockBottom/streetRoamers/richOld.png"),
	load("res://assets/Sprites/RockBottom/streetRoamers/homeless.png"),
	load("res://assets/Sprites/RockBottom/streetRoamers/averageMiddleAged.png"),
	load("res://assets/Sprites/RockBottom/streetRoamers/child.png"),
	load("res://assets/Sprites/RockBottom/streetRoamers/charityWorker.png")
	]

var productQualities = [25, 50, 75, 100]

func newStall(
	stallName:String, ownerName:String,
	ownerPortrait, lootTable:Dictionary):
	var stall = [stallName, ownerName, ownerPortrait, lootTable]
	allStalls.append(stall)
	return stall

func _ready():
	genStall()

func genStall():
	for item in productList.get_children():
		productList.remove_child(item)
		item.queue_free()
	currentStall = allStalls.pick_random()
	if !uniqueStalls.has(currentStall[0]):
		currentStall[0] = prefixes.pick_random() + " " + currentStall[0] + " " + suffixes.pick_random()
	if currentStall[1] == "random":
		currentStall[1] = genName(currentStall[0])
	ownerNameLabel.text = currentStall[1]
	if !(currentStall[2] is Texture2D):
		currentStall[2] = portraits.pick_random()
	ownerPortraitSprite.texture = currentStall[2]
	var productQualityIndex = randi_range(0, 3)
	productQuality = productQualities[productQualityIndex]
	genProducts()

func genName(inputSeed):
	var charList = []
	for character in inputSeed:
		charList.append(character)
	charList.shuffle()
	var generatedSeed = "".join(charList)
	var generator = RandomNumberGenerator.new()
	generator.seed = generatedSeed.hash()
	var firstName = generator.randi_range(0,len(dialogueLib.names)-1)
	var surname = generator.randi_range(0,len(dialogueLib.names)-1)
	return dialogueLib.names[firstName] + " " + dialogueLib.names[surname]

func genProducts():
	for item in productList.get_children():
		productList.remove_child(item)
		item.queue_free()
	
	if buyButton.pressed.is_connected(buy):
		buyButton.pressed.disconnect(self.buy)
	buyButtonContainer.hide()
		
	var tempLootTable = currentStall[3].duplicate_deep()
	var temporaryList = []
	for item in tempLootTable:
		temporaryList.append(item)
	
	var generatedIndex = 0
	
	#generate roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation largest weight / 1.25
	var roll = randfn(tempLootTable.values().max(), tempLootTable.values().max()/1.25)
	# set any generated roll above max weight to max weight - prevents out of bounds index errors
	# aka i was too lazy to make a curve resource myself so i just cannibalized and butchered a bell curve in half
	# negative roll values are fine - this just means all items in the pool are possible and they should be rare
	if (roll > tempLootTable.values().max()):
		roll = tempLootTable.values().max()
	var tempLootTableResults = []
	# if weight of item is higher than roll, add to an array
	for item in tempLootTable:
		if roll <= tempLootTable[item]:
			tempLootTableResults.append(item)
	for i in 4:
		#pick random item with even chances from said array, add to loot results
		var finalItem = tempLootTableResults.pick_random()
		# random percentage * random lootable tier, rounded to the nearest whole
		var qualityPreDeviation = snapped((productQuality * randf()), 1)
		# add deviation to quality - larger deviation range to lower qualities
		var itemQual = randi_range(qualityPreDeviation - 15, qualityPreDeviation + 5)
		# no negative qualities
		if (itemQual <= 0):
			itemQual = 1
		var itemVal = finalItem[2]
		var displayName = prefixes.pick_random() + " " + finalItem[0]
		
		productButton = TextureButton.new()
		productButton.texture_normal = finalItem[-1]
		productButton.name = finalItem[0]
		productButton.set_script(load("res://Scripts/RockBottom/productButton.gd"))
		productButton.baseInfo = finalItem
		productButton.index = generatedIndex
		productButton.pressed.connect(identifyProduct.bind(finalItem, productButton, displayName, itemQual, itemVal, finalItem[-1]))
		productList.add_child(productButton)
		productList.get_child(generatedIndex).name = finalItem[0]
		generatedIndex += 1

func identifyProduct(item, selectedProduct, displayName, itemQual, itemVal, itemTexture):
	flavourText.text = item[5]
	itemIcon.texture = item[-1]
	itemName.text = displayName
	itemQuality.icon = inventory.getStars(itemQual)
	itemQuality.text = str(itemQual) + "/100"
	var itemTrueValue = snapped(itemQual * itemVal * 0.01, 0.01)
	itemValue.text = str(itemTrueValue)
	itemDesc.itemSelected = true
	if buyButton.pressed.is_connected(buy):
		buyButton.pressed.disconnect(self.buy)
	if (selectedProduct.get_index() != null):
		buyButton.pressed.connect(buy.bind(item, selectedProduct.get_index(), itemQual, displayName, itemTrueValue, itemTexture))
	buyButtonContainer.show()

func removeProduct(listIndex):
	count = 0
	for obj in productList.get_children():
		if count == listIndex:
			productList.remove_child(obj)
			obj.queue_free()
		count += 1


func buy(item, listIndex, itemQual, itemDisplayName, itemTrueValue, itemTexture):
	if itemTrueValue < ledger.money:
		$pickProduct/itemDesc.hide()
		if ((listIndex <= productList.get_child_count() - 1)):
			if (productList.get_child(listIndex) != null):
				var obj = productList.get_child(listIndex)
				inventory.addItem(item, itemQual, itemDisplayName)
				ledger.money -= itemTrueValue
				ledger.addEntry(-itemTrueValue, clock.theTime, currentStall[0], itemDisplayName, itemTexture)
				productList.remove_child(obj)
				obj.queue_free()
				if (productList.get_child_count() == 0):
					marketOpen = false

func onButton():
	marketOpen = not marketOpen
	if marketOpen == true:
		productList.productListHidden = false
		itemName.text = ""
		itemName.show()
		buyButton.show()
		stallNameDisplay.targetText = currentStall[0]
		stallNameDisplay.fillText()
		stallNameDisplay.show()

func _process(_delta):
	if marketOpen == false:
		self.hide()
	else:
		self.show()
	if clock.theTime == 0:
		genStall()

func _on_ledger_button_open_ledger() -> void:
	marketOpen = false
func _on_sell_button_open_sell_wind() -> void:
	marketOpen = false
func _on_event_log_open_log() -> void:
	marketOpen = false
func _on_inventory_button_open_inventory() -> void:
	marketOpen = false
func _on_quota_button_open_quota() -> void:
	marketOpen = false
func _on_buy_button_open_shop() -> void:
	onButton()
func _on_vitals_button_open_vitals() -> void:
	marketOpen = false
func _on_skills_button_open_skill_tree() -> void:
	marketOpen = false
func _on_digital_clock_open_time() -> void:
	marketOpen = false
func _on_scavenge_button_open_scav_wind() -> void:
	marketOpen = false

#func _on_loot_refresh_refresh(theValue: Variant) -> void:
#	if theValue == 0.0:
#		genStall()

var prefixes = [
	"Dastardly",
	"Cowardly",
	"Heretical",
	"Demonic",
	"Evil",
	"Attractive",
	"Beautiful",
	"Clean",
	"Fancy",
	"Magnificent",
	"Ambitious",
	"Brave",
	"Jolly",
	"Silly",
	"Zealous",
	"Clumsy",
	"Fierce",
	"Mysterious",
	"Spooky",
	"Colossal",
	"Intense",
	"Puny",
	"Acidic",
	"Corny",
	"Cheesy",
	"Cruel",
	"Despicable",
	"Undying",
	"Hilarious",
	"Happy",
	"Hungry",
	"Livid",
	"Outrageous",
	"Tender",
	"Wicked",
	"Flying",
	"Genocidal",
	"Broke",
	"Gleeful"]

var suffixes = [
	"Shop",
	"Store",
	"Emporium",
	"Menagerie",
	"Hall",
	"Stall",
	"Stand",
	"Service"
]
