class_name Market
extends InventoryHelper
## Controls the market.
##
## Handles stall and product generation and sends monetary data to [Ledger].

#region variables
@onready var productList = get_node("pickProduct/productList")
@onready var buyButton = get_node("pickProduct/buyButton/interactable")
@onready var buyButtonContainer = get_node("pickProduct/buyButton")
@onready var stallNameDisplay = get_node("pickProduct/directive")
@onready var ownerPortraitSprite = get_node("pickProduct/ownerPortrait")
@onready var ownerNameLabel = get_node("pickProduct/ownerName")

@onready var ledger = get_node("../Ledger")
@onready var inventory = get_node("../inventoryWind")
@onready var clock = get_node("../../digitalClock")

@onready var itemDesc = get_node("pickProduct/itemDesc")
@onready var itemIcon = get_node("pickProduct/itemDesc/itemIcon")
@onready var itemName = get_node("pickProduct/itemDesc/Item")
@onready var infoBarOne = get_node("pickProduct/itemDesc/infoBarOne")
@onready var itemQuality = get_node("pickProduct/itemDesc/infoBarOne/Quality")
@onready var itemValue = get_node("pickProduct/itemDesc/infoBarOne/Value")
@onready var hydrationDisplay = get_node("pickProduct/itemDesc/infoBarOne/Hydration")
@onready var satiationDisplay = get_node("pickProduct/itemDesc/infoBarOne/Satiation")
@onready var flavourText = get_node("pickProduct/itemDesc/flavourText")

##Controls whether the market screen is open.
var marketOpen : bool = false
## List of all stall types registered using [method Market.newStall]. Currently unused, but can be used to iterate over all stall types in future 
## or get a stall type via an index.
var allStalls : Dictionary = {}
## Stores the current stall. Can be used to operate using that stall's properties. 
## Cannot be used to change the stall. Stall changing is not supported or planned.
var currentStall : Array
## A base quality for all products in the current stall to deviate from. Picked randomly at stall generation from [member productQualities].
var productQuality : int
## A list of potential base qualities for stalls. Used at stall generation.
var productQualities = [25, 50, 75, 100]
## List of unique/easter egg stall names.
@onready var uniqueStalls = ["Broad Street Clinic"]
## List of portraits used for stall owners.
@onready var portraits = [richOldIcon, homelessIcon, averageMiddleAgedIcon, childIcon, charityWorkerIcon]
## List of suffixes for stalls.
var suffixes = [
	"Shop",
	"Store",
	"Emporium",
	"Menagerie",
	"Hall",
	"Stall",
	"Stand",
	"Service",
]

#endregion

#region stall methods
## Registers a stall and adds it to [member allStalls] as [code]stallName:stall[/code]. [br]
## [br]
## [b]Stall Indexes: [/b] [br]
## 0 name, [br]
## 1 ownerName - if "random", generates a random name, [br]
## 2 ownerPortrait - if "random", generates a random portrait from [member portraits], [br]
## 3 lootTable. [br]
## [br]
## [b]Loot Table Format: [/b][code]item: weight[/code] [br]
## Higher weight = more frequent. Random loot is generated by grabbing random number skewed towards highest number in weight pool.
## Items with weights above generated number are added to an array, after which each loot slot randomly picks from the list with equal chances.
func newStall(
	stallName:String, ownerName:String,
	ownerPortrait, lootTable:Dictionary):
	var stall = [stallName, ownerName, ownerPortrait, lootTable]
	allStalls[stallName] = stall
	return stall
#endregion

#region stalls
@onready var broadStreetClinic = newStall("Broad Street Clinic", "Jory Tillman",
	load("res://assets/Sprites/RockBottom/lootSprites/trashCan.png"),
	{
		[
			"Crystal Wash", "Consumable", 60,
			2, 70,
			"A magical cleaning remedy that you totally shouldn't drink.",
			skincareIconSmall, skincareIcon
		]: 10,
		[
			"Healing Ointment", "Medication", 8,
			30, "null",
			"Cheap, effective health recovery. Tastes like congealed magic, though.",
			waterBottleInvIconSmall, waterBottleInvIcon
		]: 10
	}
)

@onready var snacks = newStall("Snacks", "random",
	"random",
	{
		sodaCan: 8,
		waterBottle: 8,
		cheese: 7,
		burger: 8,
	}
)

@onready var groceries = newStall("Groceries", "random",
	"random",
	{
		waterBottle: 7,
		burger: 5,
		sodaCan: 8,
		vegetables: 8,
		meats: 7,
		cheese: 8,
		soySauce: 5,
		toiletPaper: 7,
		skincare: 4,
		soySauce: 4,
	}
)

@onready var tech = newStall("Tech", "random",
	"random",
	{
		phone : 3,
		computer: 2,
		headphones: 6,
		appliance: 7
	}
)

@onready var convenience = newStall("Convenience", "random",
	"random",
	{
		waterBottle: 7,
		pencil: 8,
		pen: 5,
		sodaCan: 5,
		cardboard: 7,
		soySauce: 4,
		bag: 4,
		paper: 8,
	}
)

@onready var clothing = newStall("Clothing", "random", "random",
	{
		shirt: 7,
		sunglasses: 6,
		hat: 6,
		pants: 7,
		shorts: 8,
		hoodie: 8
	}
)
#endregion

func _ready():
	genStall()

#region generation
## Generates the day's stall and sets the screen to represent it.
func genStall():
	
	for item in productList.get_children():
		productList.remove_child(item)
		item.queue_free()
	currentStall = allStalls.values().pick_random()
	
	if !uniqueStalls.has(currentStall[0]):
		currentStall[0] = prefixes.pick_random() + " " + currentStall[0] + " " + suffixes.pick_random()
	if currentStall[1] == "random":
		currentStall[1] = genName(currentStall[0])
	ownerNameLabel.text = currentStall[1]
	if !(currentStall[2] is Texture2D):
		currentStall[2] = portraits.pick_random()
	ownerPortraitSprite.texture = currentStall[2]
	
	var productQualityIndex = randi_range(0, 3)
	productQuality = productQualities[productQualityIndex]
	genProducts()

## Generates 4 products from the current stall. [br]
## [br]
## [b]Process: [/b] [br]
## 1. Generate roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation (largest weight / 1.25).
## I was too lazy to make a curve resource myself so I just cannibalized and butchered a bell curve in half. [br]
## 2. Set any generated roll above max weight to max weight - prevents out of bounds index errors. 
## Negative roll values are fine - this just means all items in the pool are possible and they should be as rare as necessary. [br]
## 3. If weight of item is higher than roll, add to an array. [br]
## 4. Pick random item with even chances from said array, add to loot results. [br]
## 5. Generate quality per each item - random percentage * random lootable tier, rounded to the nearest whole.
## Deviate [member qualityPreDeviation] - larger deviation range to lower qualities. Set zero or negative qualities to one. [br]
## 6. Generate a name. [br]
## 7. Generate a [TextureButton] for each product.
func genProducts():
	for item in productList.get_children():
		productList.remove_child(item)
		item.queue_free()
	
	if buyButton.pressed.is_connected(buy):
		buyButton.pressed.disconnect(self.buy)
	buyButtonContainer.hide()
	
	## A deep duplicate of the stall's loot table.
	var tempLootTable = currentStall[3].duplicate_deep()
	## Keeps track of how many products have been generated and is also used to assign product [TextureButton]s an index.
	var generatedIndex = 0
	## 1. A roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation (largest weight / 1.25).
	var roll = randfn(tempLootTable.values().max(), tempLootTable.values().max()/1.25)
	# 2.
	if (roll > tempLootTable.values().max()):
		roll = tempLootTable.values().max()
	## List of items with weight higher than the roll.
	var tempLootTableResults = []
	# 3.
	for item in tempLootTable:
		if roll <= tempLootTable[item]:
			tempLootTableResults.append(item)
	for i in 4:
		# 4.
		## The final base item picked from [member tempLootTableResults]
		var finalItem = tempLootTableResults.pick_random()
		# 5.
		## Random percentage * random lootable tier, rounded to the nearest whole.
		var qualityPreDeviation = snapped((productQuality * randf()), 1)
		## Final item quality.
		var itemQual = randi_range(qualityPreDeviation - 15, qualityPreDeviation + 5)
		if (itemQual <= 0):
			itemQual = 1
		# 6.
		## Randomly generated display name.
		var displayName = prefixes.pick_random() + " " + finalItem[0]
		
		# 7.
		## Used in construction of [TextureButton]s for each product.
		var productButton = TextureButton.new()
		productButton.texture_normal = finalItem[-1]
		productButton.name = finalItem[0]
		productButton.set_script(load("res://Scripts/RockBottom/productButton.gd"))
		productButton.baseInfo = finalItem
		productButton.index = generatedIndex
		productButton.pressed.connect(generateInfo.bind(itemDesc, assembleItem(itemQual, finalItem, displayName), productButton))
		productList.add_child(productButton)
		productList.get_child(generatedIndex).name = finalItem[0]
		generatedIndex += 1
#endregion

#region buying and selecting
## Overrides [method InventoryHelper.generateInfo]. Updates the [ItemDesc] and buy button to show. Connects the buy button to the selected item.
func generateInfo(desc, item, selectedProduct := TextureButton.new()):
	super.generateInfo(desc, item)
	itemDesc.itemSelected = true
	if buyButton.pressed.is_connected(buy):
		buyButton.pressed.disconnect(self.buy)
	if (selectedProduct.get_index() != null):
		buyButton.pressed.connect(buy.bind(item, selectedProduct.get_index()))
	buyButtonContainer.show()

## Removes a product from [member productList] at specified index.
func removeProduct(listIndex):
	## Increments per every [TextureButton] in [member productList] during [method Market.removeProduct]. [br]
	## [br]
	## Can be retrieved at function end to get the index of the item just removed.
	## Unless item was at the end of [member productList] it has probably been given to another item.
	var count = 0
	for obj in productList.get_children():
		if count == listIndex:
			productList.remove_child(obj)
			obj.queue_free()
		count += 1

## Buys a product. This handles the ledger transaction and putting to inventory.
func buy(item, listIndex):
	if item[3] <= ledger.money:
		$pickProduct/itemDesc.hide()
		if ((listIndex <= productList.get_child_count() - 1)):
			if (productList.get_child(listIndex) != null):
				## The [TextureButton] associated with the selected product.
				var obj = productList.get_child(listIndex)
				inventory.addItem(item)
				ledger.money -= item[3]
				ledger.addEntry(-item[3], clock.theTime, currentStall[0], item[2], item[0][-1])
				productList.remove_child(obj)
				obj.queue_free()
				if (productList.get_child_count() == 0):
					marketOpen = false
				itemDesc.itemSelected = false
				buyButtonContainer.hide()
				
#endregion

#region screen
func onButton():
	marketOpen = not marketOpen
	if marketOpen == true:
		productList.productListHidden = false
		itemName.text = ""
		itemName.show()
		buyButton.show()
		stallNameDisplay.targetText = currentStall[0]
		stallNameDisplay.fillText()
		stallNameDisplay.show()

func _process(_delta):
	if marketOpen == false:
		self.hide()
	else:
		self.show()
	if clock.theTime == 0:
		genStall()

func _on_ledger_button_open_ledger() -> void:
	marketOpen = false
func _on_sell_button_open_sell_wind() -> void:
	marketOpen = false
func _on_event_log_open_log() -> void:
	marketOpen = false
func _on_inventory_button_open_inventory() -> void:
	marketOpen = false
func _on_quota_button_open_quota() -> void:
	marketOpen = false
func _on_buy_button_open_shop() -> void:
	onButton()
func _on_vitals_button_open_vitals() -> void:
	marketOpen = false
func _on_skills_button_open_skill_tree() -> void:
	marketOpen = false
func _on_digital_clock_open_time() -> void:
	marketOpen = false
func _on_scavenge_button_open_scav_wind() -> void:
	marketOpen = false
#endregion
