class_name StrangerList
extends HBoxContainer
## The list of strangers generated by [SellWindow].
##
## Only controls visibility based on [member peopleListHidden]. All logic is in the parent [SellWindow].

## Controls visibility.
@export var peopleListHidden = true

func _process(_delta):
	if peopleListHidden == true:
		self.hide()
	else:
		self.show()
