class_name Scavenge
extends InventoryHelper
## Controls the scavenging function of the game; lootable generation, loot minigame, and loot collection.

#region nodes
@onready var lootableList = get_node("pickLootable/lootableList")
@onready var lootButton = get_node("pickLootable/lootButton/interactable")
@onready var lootButtonContainer = get_node("pickLootable/lootButton")
@onready var directive = get_node("pickLootable/directive")
@onready var lootableDesc = get_node("pickLootable/lootableDesc")
@onready var refreshExplanation = get_node("pickLootable/explanation")
@onready var lootRefresh = get_node("pickLootable/lootRefresh")
@onready var ledger = get_node("../Ledger")
@onready var terminalText = get_node("lootResult/Terminal/termText")
@onready var terminal = get_node("lootResult/Terminal")

@onready var lootResult = get_node("lootResult")
@onready var minigameWindow = get_node("lootResult/minigameWindow")
@onready var drawn = get_node("lootResult/minigameWindow/drawn")
@onready var reference = get_node("lootResult/minigameWindow/reference")
@onready var timer = get_node("lootResult/minigameWindow/timer")

@onready var lootTurnout = get_node("lootResult/lootTurnout")
@onready var lootBox = get_node("lootResult/lootTurnout/lootBox")
@onready var takeButton = get_node("lootResult/lootTurnout/takeButton/interactable")
@onready var takeButtonContainer = get_node("lootResult/lootTurnout/takeButton")
@onready var directivePostLoot = get_node("lootResult/lootTurnout/directive")
@onready var inventory = get_node("../inventoryWind")
@onready var itemDesc = get_node("lootResult/lootTurnout/itemDesc")
@onready var itemIcon = get_node("lootResult/lootTurnout/itemDesc/itemIcon")
@onready var Item = get_node("lootResult/lootTurnout/itemDesc/Item")
@onready var infoBarOne = get_node("lootResult/lootTurnout/itemDesc/infoBarOne")
@onready var itemQuality = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Quality")
@onready var itemValue = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Value")
@onready var hydrationDisplay = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Hydration")
@onready var satiationDisplay = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Satiation")
@onready var flavourText = get_node("lootResult/lootTurnout/itemDesc/flavourText")
#endregion

#region variables
## Controls whether the window is open or not.
var scavengeOpen = false
## Updated to show whether a scavenge game is currently happening to block other things.
var scavengeActive = false
## List of all lootables registered using [method Scavenge.newLootable]. Used to get data of a lootable at runtime. Access a lootable using its name as key.
var allLootables : Dictionary = {}
## The current lootable's name, stored when in a looting game.
var storedLootable : String

## List of textures to be drawn.
@onready var referenceTextures = [
	circle,
	triangle,
	star,
	umbrella
]

## Lootables that appear at 0<=balance<=10 dollars
var lvl1Lootables : Array[String] = ["Trash Can"]
## Lootables that appear at 10<balance<=100 dollars
var lvl2Lootables : Array[String] = ["Trash Can", "Dropped Bag"]
## Lootables that appear at 100<balance<=300 dollars
var lvl3Lootables : Array[String] = ["Dropped Bag", "Discarded Package"]
## Lootables that appear at 300<balance<=700 dollars
var lvl4Lootables : Array[String] = ["Discarded Package", "Heavy Briefcase"]
#endregion

#region lootable methods
## Method for creating new lootables. Used instead of just assigning an array to operate on each lootable on ready. 
## Appends items to [member allLootables] using their name as [code]key:lootable[/code]. [br]
## [br]
## [b]Lootable Indexes:[/b] [br]
## 0 name, [br]
## 1 lootQuality acts as a base quality for loot to deviate from, [br]
## 2 containerSize is the amount of loot items, [br]
## 3 referenceImage is the index of the reference image to use in [member referenceTextures], [br]
## 4 texture, [br]
## 5 lootTable. [br]
## [br]
## [b]Loot Table Format: [/b][code]item: weight[/code] [br]
## Higher weight = more frequent. Random loot is generated by grabbing random number skewed towards highest number in weight pool.
## Items with weights above generated number are added to an array, after which each loot slot randomly picks from the list with equal chances.
func newLootable(
	lootableName:String, lootQuality:float, containerSize:int,
	referenceImage:int, texture:Texture2D, lootTable:Dictionary):
	var lootable = [lootableName, lootQuality, containerSize, referenceImage, texture, lootTable]
	allLootables[lootableName] = lootable
	return lootable
#endregion

#region lootables
@onready var trashCan = newLootable("Trash Can", 25, 5, 0,
	trashCanIcon,
	{
		waterBottle: 7,
		pencil: 8,
		burger: 6,
		appliance: 3,
		pen: 5,
		sodaCan: 5,
		vegetables: 5,
		meats: 4,
		cheese: 5,
		phone: 2,
		cardboard: 7,
		soySauce: 4,
		bag: 4,
		headphones: 3,
		paper: 8,
		shirt: 7,
		pants: 7,
		shorts: 5,
		hat: 5,
		sunglasses: 6,
		hoodie: 5,
		toiletPaper: 6,
		ponder: 1,
		skincare: 3,
		computer: 1,
		cat: 2,
		briefcase: 5,
	})
@onready var bagLootable = newLootable("Dropped Bag", 50, 4, 1,
	bagLootableIcon,
	{
		waterBottle: 7,
		burger: 5,
		pen: 5,
		sodaCan: 8,
		vegetables: 8,
		meats: 7,
		cheese: 8,
		phone: 3,
		soySauce: 5,
		bag: 8,
		headphones: 3,
		shirt: 7,
		pants: 7,
		shorts: 5,
		hat: 6,
		sunglasses: 7,
		hoodie: 6,
		toiletPaper: 7,
		ponder: 1,
		skincare: 4,
		cat: 2
	})
@onready var package = newLootable("Discarded Package", 75, 3, 2,
	packageIcon,
	{
		pencil: 5,
		appliance: 7,
		pen: 7,
		phone: 4,
		cardboard: 7,
		headphones: 6,
		paper: 8,
		shirt: 7,
		pants: 7,
		shorts: 7,
		hoodie: 8,
		ponder: 1,
		skincare: 8,
		computer: 2,
		cat: 2,
	})
@onready var briefcaseLootable = newLootable("Heavy Briefcase", 100, 2, 3,
	briefcaseLootableIcon,
	{
		paper: 6,
		sunglasses: 6,
		hoodie: 5,
		toiletPaper: 4,
		ponder: 1,
		skincare: 5,
		cat: 2,
		briefcase: 7,
		phone : 3,
		coin : 5,
		bill: 6,
		cheque: 7,
		bond: 6
	})
#endregion

func _ready():
	lootTurnout.hide()
	reset()
	for item in lootableList.get_children():
		lootableList.remove_child(item)
		item.queue_free()
	for item in lootBox.get_children():
		lootBox.remove_child(item)
		item.queue_free()
	genLootables()

func _input(event):
	if event.is_action_pressed("debug"):
		print("scavengeActive: " + str(scavengeActive))

#region generate lootables
## Generates lootables. [br]
## 1. Reset lootables. [br]
## 2. Decide how many lootables to generate. [br]
## - 0 =< balance <= 10 | 4 lootables [br]
## - 10 < balance <= 100 | 3-4 lootables [br]
## - 100 < balance <= 300 | 2-3 lootables [br]
## - 300 < balance <= 700 | 1-2 lootables [br]
## - 700 < balance | 1 lootables [br]
## 3. Pick which lootables can generate based on balance (see [member lvl1Lootables] - [member lvl4Lootables]). If balance > 700 generate any lootable. [br]
## 4. Create a matching [TextureButton].
func genLootables():
	#1.
	for item in lootableList.get_children():
		lootableList.remove_child(item)
		item.queue_free()
	
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
	lootButtonContainer.hide()
	lootableDesc.targetText = ""
	lootableDesc.fillText()
	
	#2.
	## How many lootables will be generated
	var lootableCount : int
	if ledger.money >= 0 and ledger.money <= 10:
		lootableCount = 4
	elif ledger.money > 10 and ledger.money <= 100:
		lootableCount = randi_range(3,4)
	elif ledger.money > 100 and ledger.money <= 300:
		lootableCount = randi_range(2,3)
	elif ledger.money > 300 and ledger.money <= 700:
		lootableCount = randi_range(1,2)
	else:
		lootableCount = 1

	## Keeps track of how many lootables have been generated and is also used to assign lootable [TextureButton]s an index.
	var generatedIndex = 0
	#3.
	for i in lootableCount:
		## The randomly generated lootable id.
		var randomLootable : String
		if ledger.money >= 0 and ledger.money <= 10:
			lootableCount = randi_range(4,5)
			randomLootable = lvl1Lootables.pick_random()
		elif ledger.money > 10 and ledger.money <= 100:
			lootableCount = randi_range(3,4)
			randomLootable = lvl2Lootables.pick_random()
		elif ledger.money > 100 and ledger.money <= 300:
			lootableCount = randi_range(2,3)
			randomLootable = lvl3Lootables.pick_random()
		elif ledger.money > 300 and ledger.money <= 700:
			lootableCount = randi_range(1,2)
			randomLootable = lvl4Lootables.pick_random()
		else:
			lootableCount = 1
			randomLootable = allLootables.keys().pick_random()

		#4.
		## Used in construction of [TextureButton]s for each lootable.
		var lootableButton = TextureButton.new()
		lootableButton.texture_normal = allLootables[randomLootable][4]
		lootableButton.name = allLootables[randomLootable][0]
		lootableButton.set_script(lootableButtonScript)
		lootableButton.index = generatedIndex
		lootableButton.pressed.connect(identifyTarget.bind(randomLootable, generatedIndex, allLootables[randomLootable][0]))
		lootableList.add_child(lootableButton)
		lootableList.get_child(generatedIndex).name = allLootables[randomLootable][0]
		generatedIndex += 1

## Writes the selected lootable's name to window title.
func identifyTarget(lootableID, listIndex, displayName):
	lootableDesc.targetText = displayName
	lootableDesc.fillText()
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
	lootButton.pressed.connect(loot.bind(lootableID, listIndex))
	lootButtonContainer.show()

## Generates new lootables when the time is up.
func _on_loot_refresh_refresh(theValue: Variant) -> void:
	if theValue == 0.0:
		genLootables()
#endregion

#region game management
## Removes a lootable. Called after looting.
func removeLootable(listIndex):
	## Increments during removal cycle.
	var count = 0
	for obj in lootableList.get_children():
		if count == listIndex:
			lootableList.remove_child(obj)
			obj.queue_free()
		count += 1

## Sets up the loot minigame from a lootable id. 
## Hides unnecessary aspects of the screen and shows minigame parts. 
## Resets the minigame and updates terminal text.
func loot(lootableID, listIndex):
	scavengeActive = true
	
	directive.hide()
	$pickLootable/lootableDesc.hide()
	lootButtonContainer.hide()
	lootResult.show()
	lootTurnout.hide()
	$lootResult/Terminal.show()
	lootableList.lootableListHidden = true
	minigameWindow.show()
	
	terminalText.show()
	terminalText.targetText = "> System: Cut into the lootable as accurately as possible over the guideline. Cutting outside the lines will damage loot inside."
	terminalText.fillText()
	
	reference.reset()
	drawn.reset()
	drawn.score = 0
	reference.texture = referenceTextures[allLootables[lootableID][3]]
	reference.writePixelsToArray()
	reference.countPixels()
	drawn.drawnPixels = []
	drawn.drawingOn = true
	timer.difficultyIndex = allLootables[lootableID][3]
	timer.startTimer()
	
	storedLootable = lootableID
	removeLootable(listIndex)
	

## Resets the game and loot results.
func reset():
	refreshExplanation.targetText = ""
	refreshExplanation.fillText()
	
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
		
	directive.show()
	lootableDesc.show()
	lootableDesc.text = ""
	terminalText.targetText = ""
	terminalText.fillText()
	terminal.hide()
	
	lootButtonContainer.hide()
	lootResult.hide()
	lootTurnout.hide()
	reference.reset()
	
	drawn.reset()
	drawn.score = 0
	drawn.drawnPixels = []
	drawn.drawingOn = true
	
	$pickLootable.show()

## Ends the minigame
func _on_timer_end_game() -> void:
	drawn.drawingOn = false
	drawn.reset()
	timer.value = 0
	minigameWindow.hide()
	
	lootTurnout.show()
	if (drawn.score < 0):
		drawn.score = 0
	reference.pixelCount = reference.pixelCount / 2
	
	terminalText.targetText = "> System: You scored " + str(drawn.score) + "/" + str(reference.pixelCount) + "\n Select loot to keep. Exit menu at any time to discard undesired items."
	terminalText.fillText()
	
	itemDesc.itemSelected = false
	lootTurnout.show()
	genLoot()
	
	drawn.score = 0
	drawn.drawnPixels = []
	reference.pixelCount = 0
	reference.reset()
	
	scavengeActive = false
#endregion
	
#region loot
## Called from a loot [TextureButton]. Removes the loot and adds to inventory.
func takeLoot(item, listIndex):
	if ((listIndex <= lootBox.get_child_count() - 1)):
		if (lootBox.get_child(listIndex) != null):
			## The [TextureButton] from which the loot is taken.
			var obj = lootBox.get_child(listIndex)
			inventory.addItem(item)
			lootBox.remove_child(obj)
			obj.queue_free()
			if (lootBox.get_child_count() == 0):
				reset()
				scavengeOpen = false
			takeButtonContainer.hide()
			itemDesc.itemSelected = false

## Generates loot from the [member storedLootable]. [br]
## [br]
## [b]Process: [/b] [br]
## 0. Reset the [LootBox] [br]
## 1. Generate roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation (largest weight / 1.25).
## I was too lazy to make a curve resource myself so I just cannibalized and butchered a bell curve in half. [br]
## 2. Set any generated roll above max weight to max weight - prevents out of bounds index errors. 
## Negative roll values are fine - this just means all items in the pool are possible and they should be as rare as necessary. [br]
## 3. If weight of item is higher than roll, add to an array. [br]
## 4. Pick random item with even chances from said array, add to loot results. [br]
## 5. Generate quality per each item - percentage scored * random lootable tier, rounded to the nearest whole.
## Deviate [member qualityPreDeviation] - larger deviation range to lower qualities. Set zero or negative qualities to one. [br]
## 6. Generate a name. [br]
## 7. Generate a [TextureButton] for each loot item.
func genLoot():
	#0.
	var currentLootable = allLootables[storedLootable]
	for item in lootBox.get_children():
		lootBox.remove_child(item)
		item.queue_free()
	if takeButton.pressed.is_connected(takeLoot):
		takeButton.pressed.disconnect(self.takeLoot)
	takeButtonContainer.hide()

	## A deep duplicate of the lootable's loot table.
	var tempLootTable = currentLootable[5].duplicate_deep()
	## Keeps track of how many loot items have been generated and is also used to assign loot [TextureButton]s an index.
	var generatedIndex = 0
	# 1.
	## A roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation (largest weight / 1.25).
	var roll = randfn(tempLootTable.values().max(), tempLootTable.values().max()/1.25)
	# 2.
	if (roll > tempLootTable.values().max()):
		roll = tempLootTable.values().max()
	## List of items with weight higher than the roll.
	var tempLootTableResults = []
	# 3.
	for item in tempLootTable:
		if roll <= tempLootTable[item] && generatedIndex < currentLootable[2]:
			tempLootTableResults.append(item)
	for i in currentLootable[2]:
		# 4.
		## The final base item picked from [member tempLootTableResults]
		var finalItem = tempLootTableResults.pick_random()
		# 5.
		## The score from the game as a percentage
		var scorePercentage = snapped((drawn.score / reference.pixelCount), 0.01)
		## Percentage scored * random lootable tier, rounded to the nearest whole.
		var qualityPreDeviation = snapped((allLootables[storedLootable][1] * scorePercentage), 1)
		## Final item quality.
		var itemQual = randi_range(qualityPreDeviation - 15, qualityPreDeviation + 5)
		if (itemQual <= 0):
			itemQual = 1
		# 6.
		## Randomly generated display name.
		var displayName = prefixes.pick_random() + " " + finalItem[0]
		
		# 7.
		## Used in construction of [TextureButton]s for each loot item.
		var takeableLootButton = TextureButton.new()
		takeableLootButton.texture_normal = finalItem[-1]
		takeableLootButton.texture_pressed = finalItem[-2]
		takeableLootButton.name = finalItem[0]
		takeableLootButton.set_script(takeableLootButtonScript)
		takeableLootButton.index = generatedIndex
		var assembledItem = assembleItem(itemQual, finalItem, displayName)
		takeableLootButton.pressed.connect(generateInfo.bind(itemDesc, assembledItem, takeableLootButton))
		lootBox.add_child(takeableLootButton)
		lootBox.get_child(takeableLootButton.get_index()).name = finalItem[0]
		generatedIndex += 1

## Overrides [method InventoryHelper.generateInfo]. Updates the [ItemDesc] and take button to show. Connects the take button to the selected item.
func generateInfo(desc, item, selectedLoot := TextureButton.new()):
	terminalText.hide()
	super.generateInfo(desc, item)
	itemDesc.itemSelected = true
	if takeButton.pressed.is_connected(takeLoot):
		takeButton.pressed.disconnect(self.takeLoot)
	if (selectedLoot.get_index() != null):
		takeButton.pressed.connect(takeLoot.bind(item, selectedLoot.get_index()))
	takeButtonContainer.show()

#region screen
func onButton():
	lootResult.hide()
	terminalText.targetText = ""
	terminalText.fillText()
	reset()
	scavengeOpen = not scavengeOpen
	if scavengeOpen == true:
		lootableList.lootableListHidden = false
		lootableDesc.text = ""
		lootableDesc.show()
		directive.targetText = "Lootables Identified"
		directive.fillText()
		refreshExplanation.targetText = "Until new lootables"
		refreshExplanation.fillText()
		directive.show()

func _process(_delta):
	if scavengeOpen == false:
		self.hide()
	else:
		self.show()

func _on_ledger_button_open_ledger() -> void:
	scavengeOpen = false
func _on_sell_button_open_sell_wind() -> void:
	scavengeOpen = false
func _on_event_log_open_log() -> void:
	scavengeOpen = false
func _on_inventory_button_open_inventory() -> void:
	scavengeOpen = false
func _on_quota_button_open_quota() -> void:
	scavengeOpen = false
func _on_buy_button_open_shop() -> void:
	scavengeOpen = false
func _on_vitals_button_open_vitals() -> void:
	scavengeOpen = false
func _on_skills_button_open_skill_tree() -> void:
	scavengeOpen = false
func _on_digital_clock_open_time() -> void:
	scavengeOpen = false

func _on_scavenge_button_open_scav_wind() -> void:
	onButton()
#endregion
