extends Node2D

var scavengeOpen = false

@onready var lootableList = get_node("pickLootable/lootableList")
@onready var lootButton = get_node("pickLootable/lootButton/interactable")
@onready var lootButtonContainer = get_node("pickLootable/lootButton")
@onready var directive = get_node("pickLootable/directive")
@onready var lootableDesc = get_node("pickLootable/lootableDesc")
@onready var refreshExplanation = get_node("pickLootable/explanation")
@onready var lootRefresh = get_node("pickLootable/lootRefresh")
@onready var ledger = get_node("../Ledger")
@onready var terminalText = get_node("lootResult/Terminal/termText")
@onready var terminal = get_node("lootResult/Terminal")

@onready var lootResult = get_node("lootResult")
@onready var minigameWindow = get_node("lootResult/minigameWindow")
@onready var drawn = get_node("lootResult/minigameWindow/drawn")
@onready var reference = get_node("lootResult/minigameWindow/reference")
@onready var timer = get_node("lootResult/minigameWindow/timer")

@onready var lootTurnout = get_node("lootResult/lootTurnout")
@onready var lootBox = get_node("lootResult/lootTurnout/lootBox")
@onready var takeButton = get_node("lootResult/lootTurnout/takeButton/interactable")
@onready var takeButtonContainer = get_node("lootResult/lootTurnout/takeButton")
@onready var directivePostLoot = get_node("lootResult/lootTurnout/directive")
@onready var inventory = get_node("../inventoryWind")
@onready var itemDesc = get_node("lootResult/lootTurnout/itemDesc")
@onready var itemIcon = get_node("lootResult/lootTurnout/itemDesc/itemIcon")
@onready var Item = get_node("lootResult/lootTurnout/itemDesc/Item")
@onready var infoBarOne = get_node("lootResult/lootTurnout/itemDesc/infoBarOne")
@onready var itemQuality = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Quality")
@onready var itemValue = get_node("lootResult/lootTurnout/itemDesc/infoBarOne/Value")
@onready var flavourText = get_node("lootResult/lootTurnout/itemDesc/flavourText")


var count
var lootableButton
var lootableCount
var lootCount
var curSelPlace
var allLootables = []
var storedLootable:int

@onready var circle = load("res://assets/Sprites/RockBottom/minigames/circle.png")
@onready var triangle = load("res://assets/Sprites/RockBottom/minigames/triangle.png")
@onready var star = load("res://assets/Sprites/RockBottom/minigames/star.png")
@onready var umbrella = load("res://assets/Sprites/RockBottom/minigames/umbrella.png")
@onready var referenceTextures = [
	circle,
	triangle,
	star,
	umbrella
]

# 0 name, 1 lootQuality, 2 containerSize, 3 difficulty, 4 texture, 5 lootTable
# lootTable formatting
# inventory.item: weight
# Weight - higher = more frequent.
# Random loot is generated by grabbing random number skewed towards highest number in weight pool.
# Items with weights above generated number are added to an array,
# after which each loot slot randomly picks from the list with equal chances

@onready var trashCan = newLootable("Trash Can", 25, 5, 0,
	load("res://assets/Sprites/RockBottom/lootSprites/trashCan.png"),
	{
		inventory.waterBottle: 7,
		inventory.pencil: 8,
		inventory.burger: 6,
		inventory.appliance: 3,
		inventory.pen: 5,
		inventory.sodaCan: 5,
		inventory.vegetables: 5,
		inventory.meats: 4,
		inventory.cheese: 5,
		inventory.phone: 2,
		inventory.cardboard: 7,
		inventory.soySauce: 4,
		inventory.bag: 4,
		inventory.headphones: 3,
		inventory.paper: 8,
		inventory.clothes: 5,
		inventory.toiletPaper: 6,
		inventory.ponder: 1,
		inventory.skincare: 3,
		inventory.computer: 1,
		inventory.cat: 2,
		inventory.briefcase: 5,
	})
@onready var bag = newLootable("Dropped Bag", 50, 4, 1,
	load("res://assets/Sprites/RockBottom/lootSprites/bag.png"),
	{
		inventory.waterBottle: 7,
		inventory.burger: 5,
		inventory.pen: 5,
		inventory.sodaCan: 8,
		inventory.vegetables: 8,
		inventory.meats: 7,
		inventory.cheese: 8,
		inventory.phone: 3,
		inventory.soySauce: 5,
		inventory.bag: 8,
		inventory.headphones: 3,
		inventory.clothes: 7,
		inventory.toiletPaper: 7,
		inventory.ponder: 1,
		inventory.skincare: 4,
		inventory.cat: 2
	})
@onready var package = newLootable("Discarded Package", 75, 3, 2,
	load("res://assets/Sprites/RockBottom/lootSprites/package.png"),
	{
		inventory.pencil: 5,
		inventory.appliance: 7,
		inventory.pen: 7,
		inventory.phone: 4,
		inventory.cardboard: 7,
		inventory.headphones: 6,
		inventory.paper: 8,
		inventory.clothes: 9,
		inventory.ponder: 1,
		inventory.skincare: 8,
		inventory.computer: 2,
		inventory.cat: 2,
	})
@onready var briefcase = newLootable("Heavy Briefcase", 100, 2, 3,
	load("res://assets/Sprites/RockBottom/lootSprites/briefcase.png"),
	{
		inventory.paper: 6,
		inventory.clothes: 5,
		inventory.toiletPaper: 4,
		inventory.ponder: 1,
		inventory.skincare: 5,
		inventory.cat: 2,
		inventory.briefcase: 7,
		inventory.phone : 3,
		inventory.coin : 5,
		inventory.bill: 6,
		inventory.cheque: 7,
		inventory.bond: 6
	})

func newLootable(
	lootableName:String, lootQuality:float, containerSize:int,
	difficulty:float, texture:Texture2D, lootTable:Dictionary):
	var lootable = [lootableName, lootQuality, containerSize, difficulty, texture, lootTable]
	allLootables.append(lootable)
	return lootable

func _ready():
	lootTurnout.hide()
	reset()
	for item in lootableList.get_children():
		lootableList.remove_child(item)
		item.queue_free()
	for item in lootBox.get_children():
		lootBox.remove_child(item)
		item.queue_free()
	genLootables()

func genLootables():
	for item in lootableList.get_children():
		lootableList.remove_child(item)
		item.queue_free()
	
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
	lootButtonContainer.hide()
	lootableDesc.targetText = ""
	lootableDesc.fillText()
	
	var temporaryList = []
	for item in allLootables:
		temporaryList.append(item)
	
	#pick how many lootables based on money count - higher money less lootables
	if ledger.money >= 0 and ledger.money <= 10:
		lootableCount = 4
	elif ledger.money > 10 and ledger.money <= 100:
		lootableCount = randi_range(3,4)
	elif ledger.money > 100 and ledger.money <= 300:
		lootableCount = randi_range(2,3)
	elif ledger.money > 300 and ledger.money <= 700:
		lootableCount = randi_range(1,2)
	else:
		lootableCount = 1

	var generatedIndex = 0
	for i in lootableCount:
		#pick lootables available via money, higher money = higher level lootables
		var randomRegistryIndex:int
		if ledger.money >= 0 and ledger.money <= 10:
			lootableCount = randi_range(4,5)
			randomRegistryIndex = randi_range(0, (len(temporaryList) - 4))
		elif ledger.money > 10 and ledger.money <= 100:
			lootableCount = randi_range(3,4)
			randomRegistryIndex = randi_range(0, (len(temporaryList) - 3))
		elif ledger.money > 100 and ledger.money <= 300:
			lootableCount = randi_range(2,3)
			randomRegistryIndex = randi_range(0, (len(temporaryList) - 2))
		elif ledger.money > 300 and ledger.money <= 700:
			lootableCount = randi_range(1,2)
			randomRegistryIndex = randi_range(0, (len(temporaryList) - 1))
		else:
			lootableCount = 1
			randomRegistryIndex = randi_range(0, (len(temporaryList) - 4))

		lootableButton = TextureButton.new()
		lootableButton.texture_normal = allLootables[randomRegistryIndex][4]
		lootableButton.name = allLootables[randomRegistryIndex][0]
		lootableButton.set_script(load("res://Scripts/RockBottom/lootableButton.gd"))
		lootableButton.baseInfo = allLootables[randomRegistryIndex]
		lootableButton.index = generatedIndex
		lootableButton.pressed.connect(identifyTarget.bind(randomRegistryIndex, generatedIndex, allLootables[randomRegistryIndex][0]))
		lootableList.add_child(lootableButton)
		lootableList.get_child(generatedIndex).name = allLootables[randomRegistryIndex][0]
		generatedIndex += 1

func identifyTarget(registryIndex, listIndex, displayName):
	lootableDesc.targetText = displayName
	lootableDesc.fillText()
	#haggle.storedStrangerIndex = place
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
	lootButton.pressed.connect(loot.bind(registryIndex, listIndex))
	lootButtonContainer.show()

func removeLootable(listIndex):
	count = 0
	for obj in lootableList.get_children():
		if count == listIndex:
			lootableList.remove_child(obj)
			obj.queue_free()
		count += 1

#registryIndex refers to allLootables, listIndex refers to the lootableList node
func loot(registryIndex, listIndex):
	curSelPlace = listIndex
	directive.hide()
	$pickLootable/lootableDesc.hide()
	lootButtonContainer.hide()
	lootResult.show()
	lootTurnout.hide()
	$lootResult/Terminal.show()
	lootableList.lootableListHidden = true
	minigameWindow.show()
	terminalText.show()
	terminalText.targetText = "> System: Cut into the lootable as accurately as possible over the guideline. Cutting outside the lines will damage loot inside."
	terminalText.fillText()
	reference.reset()
	drawn.reset()
	drawn.score = 0
	reference.texture = referenceTextures[allLootables[registryIndex][3]]
	reference.writePixelsToArray()
	reference.countPixels()
	drawn.drawnPixels = []
	drawn.drawingOn = true
	timer.difficultyIndex = allLootables[registryIndex][3]
	storedLootable = registryIndex
	timer.startTimer()
	

func reset():
	curSelPlace = "None"
	refreshExplanation.targetText = ""
	refreshExplanation.fillText()
	if lootButton.pressed.is_connected(loot):
		lootButton.pressed.disconnect(self.loot)
	directive.show()
	lootableDesc.show()
	lootableDesc.text = ""
	terminalText.targetText = ""
	terminalText.fillText()
	terminal.hide()
	lootButtonContainer.hide()
	lootResult.hide()
	lootTurnout.hide()
	reference.reset()
	drawn.reset()
	drawn.score = 0
	drawn.drawnPixels = []
	drawn.drawingOn = true
	$pickLootable.show()

func onButton():
	lootResult.hide()
	terminalText.targetText = ""
	terminalText.fillText()
	reset()
	scavengeOpen = not scavengeOpen
	if scavengeOpen == true:
		lootableList.lootableListHidden = false
		lootableDesc.text = ""
		lootableDesc.show()
		directive.targetText = "Lootables Identified"
		directive.fillText()
		refreshExplanation.targetText = "Until new lootables"
		refreshExplanation.fillText()
		directive.show()

func _process(_delta):
	if scavengeOpen == false:
		self.hide()
	else:
		self.show()

func _on_ledger_button_open_ledger() -> void:
	scavengeOpen = false
func _on_sell_button_open_sell_wind() -> void:
	scavengeOpen = false
func _on_event_log_open_log() -> void:
	scavengeOpen = false
func _on_inventory_button_open_inventory() -> void:
	scavengeOpen = false
func _on_quota_button_open_quota() -> void:
	scavengeOpen = false
func _on_buy_button_open_shop() -> void:
	scavengeOpen = false
func _on_vitals_button_open_vitals() -> void:
	scavengeOpen = false
func _on_skills_button_open_skill_tree() -> void:
	scavengeOpen = false
func _on_digital_clock_open_time() -> void:
	scavengeOpen = false

func _on_scavenge_button_open_scav_wind() -> void:
	onButton()

func _on_loot_refresh_refresh(theValue: Variant) -> void:
	if theValue == 0.0:
		genLootables()

func _on_timer_end_game() -> void:
	drawn.drawingOn = false
	drawn.reset()
	timer.value = 0
	minigameWindow.hide()
	lootTurnout.show()
	if (drawn.score < 0):
		drawn.score = 0
	reference.pixelCount = reference.pixelCount / 2
	terminalText.targetText = "> System: You scored " + str(drawn.score) + "/" + str(reference.pixelCount) + "\n Select loot to keep. Exit menu at any time to discard undesired items."
	terminalText.fillText()
	itemDesc.itemSelected = false
	lootTurnout.show()
	genLoot()
	drawn.score = 0
	drawn.drawnPixels = []
	reference.pixelCount = 0
	reference.reset()
	
func takeLoot(item, listIndex, itemQ, itemName):
	if ((listIndex <= lootBox.get_child_count() - 1)):
		if (lootBox.get_child(listIndex) != null):
			var obj = lootBox.get_child(listIndex)
			inventory.addItem(item, itemQ, itemName)
			lootBox.remove_child(obj)
			obj.queue_free()
			if (lootBox.get_child_count() == 0):
				reset()
				scavengeOpen = false

func genLoot():
	var currentLootable = allLootables[storedLootable]
	for item in lootBox.get_children():
		lootBox.remove_child(item)
		item.queue_free()
	
	if takeButton.pressed.is_connected(takeLoot):
		takeButton.pressed.disconnect(self.takeLoot)
	takeButtonContainer.hide()
	
	if currentLootable[2] > 1 and currentLootable[2] <= 2:
		lootCount = randi_range(1,2)
	elif currentLootable[2] > 2 and currentLootable[2] <= 3:
		lootCount = randi_range(2,3)
	elif currentLootable[2] > 3 and currentLootable[2] <= 4:
		lootCount = randi_range(3,4)
	elif currentLootable[2] > 4 and currentLootable[2] <= 5:
		lootCount = randi_range(4,5)
	else:
		lootCount = 0

	var tempLootTable = currentLootable[5].duplicate_deep()
	var temporaryList = []
	for item in tempLootTable:
		temporaryList.append(item)
	
	var generatedIndex = 0
	
	#generate roll based on a bell curve from 0 to largest weight value in loot table, with standard deviation largest weight / 1.25
	var roll = randfn(tempLootTable.values().max(), tempLootTable.values().max()/1.25)
	# set any generated roll above max weight to max weight - prevents out of bounds index errors
	# aka i was too lazy to make a curve resource myself so i just cannibalized and butchered a bell curve in half
	# negative roll values are fine - this just means all items in the pool are possible and they should be rare
	if (roll > tempLootTable.values().max()):
		roll = tempLootTable.values().max()
	var tempLootTableResults = []
	# if weight of item is higher than roll, add to an array
	for item in tempLootTable:
		if roll <= tempLootTable[item] && generatedIndex < currentLootable[2]:
			tempLootTableResults.append(item)
	for i in currentLootable[2]:
			#pick random item with even chances from said array, add to loot results
			var finalItem = tempLootTableResults.pick_random()
			
			var scorePercentage = snapped((drawn.score / reference.pixelCount), 0.01)
			# percentage scored * lootable tier * 25, rounded to the nearest whole
			var qualityPreDeviation = snapped((allLootables[storedLootable][1] * scorePercentage), 1)
			# add deviation to quality - larger deviation range to lower qualities
			var itemQual = randi_range(qualityPreDeviation - 15, qualityPreDeviation + 5)
			# no negative qualities
			if (itemQual <= 0):
				itemQual = 1
			var itemVal = finalItem[2]
			var displayName = prefixes.pick_random() + " " + finalItem[0]
			
			var takeableLootButton = TextureButton.new()
			takeableLootButton.texture_normal = finalItem[-1]
			takeableLootButton.name = finalItem[0]
			takeableLootButton.set_script(load("res://Scripts/RockBottom/takeableLootButton.gd"))
			takeableLootButton.baseInfo = finalItem
			takeableLootButton.index = generatedIndex
			takeableLootButton.pressed.connect(identifyLoot.bind(finalItem, takeableLootButton, displayName, itemQual, itemVal))
			
			lootBox.add_child(takeableLootButton)
			lootBox.get_child(takeableLootButton.get_index()).name = finalItem[0]
			generatedIndex += 1

func identifyLoot(item, selectedLoot, displayName, itemQual, itemVal):
	terminalText.hide()
	flavourText.text = item[5]
	itemIcon.texture = item[-1]
	Item.text = displayName
	itemQuality.icon = inventory.getStars(itemQual)
	itemQuality.text = str(itemQual) + "/100"
	itemValue.text = str(snapped(itemQual * itemVal * 0.01, 0.01))
	itemDesc.itemSelected = true
	if takeButton.pressed.is_connected(takeLoot):
		takeButton.pressed.disconnect(self.takeLoot)
	if (selectedLoot.get_index() != null):
		takeButton.pressed.connect(takeLoot.bind(item, selectedLoot.get_index(), itemQual, displayName))
	takeButtonContainer.show()

var prefixes = [
	"Dastardly",
	"Cowardly",
	"Heretical",
	"Demonic",
	"Evil",
	"Attractive",
	"Beautiful",
	"Clean",
	"Fancy",
	"Magnificent",
	"Ambitious",
	"Brave",
	"Jolly",
	"Silly",
	"Zealous",
	"Clumsy",
	"Fierce",
	"Mysterious",
	"Spooky",
	"Colossal",
	"Intense",
	"Puny",
	"Acidic",
	"Corny",
	"Cheesy",
	"Cruel",
	"Despicable",
	"Undying",
	"Hilarious",
	"Happy",
	"Hungry",
	"Livid",
	"Outrageous",
	"Tender",
	"Wicked",
	"Flying",
	"Genocidal",
	"Broke",
	"Gleeful"]
